function tau_M = torque_matrix(r,theta)
%TORQUE_MATRIX
%    tau_M = TORQUE_MATRIX(R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Jun-2024 11:02:56

%%pixxel all thrusters around x axis
t2 = cos(theta);
t3 = sin(theta);
t4 = r.*t2;
t5 = r.*t3;
t6 = -t4;
t7 = -t5;
tau_M = reshape([t5,t6,0.0,t7,0.0,t6,t5,t4,0.0,t7,0.0,t4],[3,4]);
end
